---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    type: service
    tier: network
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    type: db
    tier: backend
    app: demo-voting-app