---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    type: service
    tier: network
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    name: result-app-pod
    type: webapp
    tier: frontend
    app: demo-voting-app