apiVersion: v1
kind: Config

cuttent-context: dev@google	# default context with run kubectl without parametrs 

clusters:

- name: my-kube-playground
  cluster:
    certificate-authority: ca.crt
    server: https://my-kube-playground:6443
- name: development
  ...
- name: google
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZJakNDQkFxZ0F3SUJBZ0lTQlBMd2s3QjB5UzVaK0Q5MDYyWktxUkVNTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlNekF6TWpneE16QXdORGRhRncweU16QTJNall4TXpBd05EWmFNQmd4RmpBVUJnTlZCQU1NCkRTb3VaM0p2ZFhCbWN5NXVaWFF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzkKbkxkemlxVGgrdzMzbllBRWtiZE1ZV1g4M2VRa0RBYUNTK3l4cXdSRmpQL0JscTJhZlFvU0c3Y1lmWFk2MWgydgp6R0IvZkpzVWh5QzlySSt2RUU3bkhTdDdhT0FCWm5CSHYwNS9nanpxT3ErekNPRlpnVkFjQlpDRjFOR0J1aG5xCnZhTmNJcVhIbm5na1FOb1JYS285VDNhSWkxcC9UN1lQNEM0N3RkNGcrQzBZZnhtWEwvWC91eUlaSlR4QStiamEKaFFQZjFkSklxeDk2MTRrSy9iMmlaQUJ5T1gzeHZTWk01NEVqU1c5bDNxc2VSVFFvVDF6V092bmV1MVluajNqcQowL3hvSHROakVWSlBZSmJKZ3NvcktISkVxSkthTmoxTWJxNytCYzZpeTNzVTFvMW9uOUdBQ2t3T1FpVERaNHIrCm94NTkzWHNQWStkblhGVGxHWno1QWdNQkFBR2pnZ0pLTUlJQ1JqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWUQKVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwTwpCQllFRkZsRm1JaHptTjBKQXB4VEkxd216SlBOd0s0Rk1COEdBMVVkSXdRWU1CYUFGQlF1
    server: https://gcp.engine.google.com:6443
- name: production
  ...


contexts:

- name: mk-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: mk-admin
- name: dev@google
  context:
    cluster: google
    user: dev
    namespace: develop-env
- name: admin@production
  ...
- name: prod-user@development
  ...


users:

- name: mk-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key
- name; dev
- name: admin
- name: prod-user
