apiVersion: v1
kind: PersistentVolume
metadata:
  name: pers_vol1
spec:
  accessModes:
  - ReadWriteOnce	# Can be :	ReadWriteOnce	ReadWriteMany	ReadOnlyMany
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: ebs-eu3-point2	# example vol.id
    fsType: ext4
