apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: web-app
    tier: front-end
spec:
  containers:
  - name: nginx-web
    image: nginx
    env:
    - name: USER_PASSWORD
      value: somesecretpassword
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
