apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pers_claim_vol1
spec:
  accessModes:
  - ReadWriteOnce	
  storageClassName: sc_name_priviously_cleated 		# can be used for Dynamic Persistent Volume Provisioning 
  resources:
    requests:
      storage: 8Gi  
