apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: web-app
        tier: front-end
    spec:
      containers:
      - name: nginx-web
        image: nginx
        env:
        - name: USER_PASSWORD
          value: somesecretpassword
  replicas: 3
  selector:
    matchLabels:
      tier: front-end     # it related to labels in template-metadata
    
