apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: 4oCYbXlzcWzigJk=
  DB_User: 4oCYcm9vdOKAmQ==
  DB_Pasword: 4oCYcGFzc3dvcmTigJk=

# echo -n ‘mysql’ | base64
# echo -n ‘root’ | base64
# echo -n ‘password’ | base64
